trigger:
- main
pool:
#  vmImage: ubuntu-latest
 name: MyAgentPool
variables: 
  buildConfiguration: 'Release"'  
steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'